"""
This patterns is to extract discourse markers from your documents.
I transferred and modified the below link into python regex.
- https://app.quesbook.com/act/study/list-of-discourse-markers

"""
patters = {
    'addition': [
        'above all',
        'additionally',
        'again',
        'also',
        'and',
        'as well as',
        'at the same time',
        'besides',
        r'either (...) or',
        'equally important',
        'furthermore',
        'in addition',
        'least of all',
        'likewise',
        'moreover',
        'more importantly',
        'most of all',
        r'neither (...) nor',
        r'not only (...) but also',
        'too',
        "what's more"
    ],
    'cause_and_effect': [
        'as',
        'as a consequence of',
        'as a result',
        'as it is',
        'as it was',
        'because',
        'consequently',
        'due to',
        'hence',
        'in response',
        'so',
        'since',
        'therefore',
        'thus'
    ],
    'comparison': [
        'as',
        'as well as',
        'equally',
        'exactly',
        'identically',
        'in comparison',
        'in much the same way',
        'in relation to',
        'like',
        'matching',
        'of little difference',
        'parallel to',
        'resembling',
        'same as',
        'similar to',
        'similarly'
    ],
    'concession_and_qualification': [
        'a striking difference',
        'accepting that',
        'admittedly',
        'after all',
        'against',
        'allowing that',
        'although',
        'and yet',
        'another distinction',
        'but',
        'by contrast',
        'despite',
        'doubtless',
        'even so',
        'for all that',
        'fortunately',
        'granted that',
        'however',
        'indeed',
        'if',
        'in another way',
        'in contrast',
        'in one way',
        'in opposition to',
        'in spite of',
        'instead',
        'it is true that',
        'it may well be',
        'naturally',
        'nevertheless',
        'no doubt',
        'nonetheless',
        'of course',
        'on one hand',
        'on the other hand',
        'on the contrary',
        'opposite',
        'otherwise',
        'still',
        'though',
        'to differ from',
        'to oppose',
        'unexpectedly',
        'unfortunately',
        'unlike',
        'until',
        'versus',
        'without',
        'while it is true',
        'yet'
    ],
    'conclusion_and_summation': [
        'finally',
        'in conclusion',
        'in short',
        'last of all',
        'to close',
        'to conclude',
        'to end',
        'to recapitulate',
        'to sum up',
        'to summarize'
    ],
    'contrast': [
        'against',
        'although',
        'be that as it may',
        'besides',
        'but',
        'by contrast',
        'despite',
        'despite this fact',
        'even so',
        'however',
        'in contrast',
        'in one way',
        'in opposition to',
        'in spite of',
        'instead',
        'nevertheless',
        'on one hand',
        'on the contrary',
        'on the other hand',
        'opposite',
        'otherwise',
        'still',
        'though',
        'unlike',
        'versus',
        'yet'
    ],
    'generalization': [
        'above all',
        'as a rule',
        'broadly speaking',
        'chiefly',
        'essentially',
        'generally',
        'in essence',
        'in general',
        'in most cases',
        'largely',
        'mostly',
        'on the whole',
        'primarily',
        'to some extent',
        'usually'
    ],
    'emphasis': [
        'above all',
        'absolutely',
        'actually',
        'after all',
        'as a matter of fact',
        'clearly',
        'certainly',
        'chiefly',
        'each and every',
        'especially',
        'extremely',
        'furthermore',
        'in fact',
        'in truth',
        'indeed',
        'more and more',
        'more importantly',
        'moreover',
        'most important of all',
        'most of all',
        'obviously',
        'of major interest',
        'significantly',
        'surely',
        'the chief characteristic',
        'the climax of',
        'the main issue is',
        'the major point',
        'the most necessary',
        'the most significant',
        'to add to that',
        'to be sure',
        'to culminate',
        'to emphasize',
        'to highlight',
        'to stress',
        'undoubtedly',
        'unquestionably',
        'without a doubt',
        'without question'
    ],
    'illustration_and_exemplification': [
        'as an example',
        'as illustrated by',
        'as revealed by',
        'for example',
        'for instance',
        'in other words',
        'in particular',
        'in the case of',
        'in this case',
        'indeed',
        'namely',
        'such as',
        'suppose that',
        'thus',
        'to demonstrate',
        'to explain',
        'to illustrate',
        'to show',
        'specifically',
        'to be exact',
        'which',
        'when',
        'where',
        'who',
        'whom',
        'whose'
    ],
    'repetition_and_reiteration': [
        'again',
        'as stated',
        'in fact',
        'in other words',
        'in particular',
        'in short',
        'in simpler terms',
        'that is to say',
        'to clarify',
        'to explain',
        'to outline',
        'to paraphrase',
        'to put it in another way',
        'to put it differently',
        'to repeat',
        'to rephrase',
        'to restate',
        'to review',
        'to summarize'
    ],
    'time_markers_and_sequencing': [
        'after',
        'after that',
        'all at once',
        'all the time',
        'all the while',
        'always',
        'as',
        'as long as',
        'as soon as',
        'as first',
        'as last',
        'at present',
        'at the beginning',
        'at the end',
        'at the same time',
        'before',
        'by now',
        'consequently',
        'currently',
        'directly',
        'during',
        'earlier',
        'eventually',
        'finally',
        'first',
        'firstly',
        'following',
        'following that',
        'formerly',
        'from this point',
        'frequently',
        'generally',
        'gradually',
        'henceforth',
        'immediately',
        'initially',
        'in the end',
        'in the first place',
        'in the second place',
        'in the third place',
        'in the future',
        'in the meantime',
        'infrequently',
        'instantly',
        'just then',
        'lastly',
        'last of all',
        'later',
        'later on',
        'little by little',
        'meanwhile',
        'never',
        'next',
        'not at all',
        'not long ago',
        'now',
        'occasionally',
        'often',
        'on the next occasion',
        'one time',
        'once',
        'once again',
        'periodically',
        'presently',
        'previously',
        'quickly',
        'rarely',
        'recently',
        'repeatedly',
        'second',
        'third',
        'secondly',
        'thirdly',
        'seldom',
        'simultaneously',
        'since',
        'slowly',
        'so far',
        'some of the time',
        'sometimes',
        'soon',
        'starting with',
        'subsequently',
        'suddenly',
        'temporarily',
        'the following week',
        'the next time',
        'then',
        'to begin with',
        'today',
        'tomorrow',
        'until',
        'usually',
        'when',
        'while',
        'without exception',
        'yesterday'
    ]
}
